name: Run MemorySanitizer

on:
  push:

jobs:
  run-msan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        with:
          ref: aeb660ba58b89b8f9eb05cc1c81d9aad7d66946e

      - name: Install dependencies for project (Linux)
        if: runner.os == 'Linux'
        run: | 
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev \
          libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev \
          libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 \
          python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo \
          uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          
      - name: Install dependencies for project (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install coreutils diffutils findutils gawk gnu-getopt gnu-tar grep make ncurses pkg-config wget quilt xz
          brew install gcc@11
          echo 'export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"' >> ~/.bashrc
          echo 'export PATH="/opt/homebrew/opt/findutils/libexec/gnubin:$PATH"' >> ~/.bashrc
          echo 'export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"' >> ~/.bashrc
          echo 'export PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"' >> ~/.bashrc
          echo 'export PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"' >> ~/.bashrc
          echo 'export PATH="/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH"' >> ~/.bashrc
          echo 'export PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"' >> ~/.bashrc
          source ~/.bashrc
          
      - name: Build repository (Linux)
        if: runner.os == 'Linux'
        run: | 
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make download -j8
          make V=s -j$(nproc)

      - name: Build repository (macOS)
        if: runner.os == 'macOS' 
        run: bash

      - name: Install MemorySanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools

      - name: Install MemorySanitizer dependencies (macOS) 
        if: runner.os == 'macOS' 
        run: |
          brew update
          brew install llvm ninja coreutils
      
      - name: Run Google Memory Sanitizer (source code) (Linux)
        if: runner.os == 'Linux'
        run: |
          #!/bin/bash
          set +e 

          files=$(find . -type f)
          failed_compilations=0
          successful_compilations=0
          TIMEOUT_DURATION=10

          for file in $files; do
              if [[ "$file" == *.c || "$file" == *.cpp ]]; then
                  include_dirs=$(find . -name '*.h' -exec dirname {} + | sort -u | sed 's/^/-I /')
                  if ! timeout 60 clang -I "$include_dirs" -fsanitize=memory -fPIE -pie -O2 -fno-omit-frame-pointer -fsanitize-memory-track-origins -g "$file" -o ./compiled.out > /dev/null 2> /tmp/clang_errors.txt; then
                      exit_code=$?
                      if [ $exit_code -eq 1 ]; then
                          ((failed_compilations += 1))
                      fi
                      continue  # Skip to the next file on compilation error
                  fi

                  timeout $TIMEOUT_DURATION ./compiled.out
                  exit_status=$?

                  if [ $exit_status -eq 1 ]; then
                      ((successful_compilations += 1))
                      echo -e "\a"
                  else
                      ((failed_compilations += 1))
                  fi

                  rm -f ./compiled.out
              fi
          done
          echo -e "\a"

          echo "Memory Sanitizer Failures: $failed_compilations"
          echo "Memory Sanitizer Successes: $successful_compilations"

      - name: Run Google Memory Sanitizer (source code) (macOS)
        if: runner.os == 'macOS'
        run: |
          #!/bin/bash
          set +e 

          files=$(find . -type f)
          failed_compilations=0
          successful_compilations=0
          TIMEOUT_DURATION=10

          for file in $files; do
              if [[ "$file" == *.c || "$file" == *.cpp ]]; then
                  include_dirs=$(find . -name '*.h' -exec dirname {} + | sort -u | sed 's/^/-I /')
                  if ! timeout 60 clang -I "$include_dirs" -fsanitize=memory -fPIE -pie -O2 -fno-omit-frame-pointer -fsanitize-memory-track-origins -g "$file" -o ./compiled.out > /dev/null 2> /tmp/clang_errors.txt; then
                      exit_code=$?
                      if [ $exit_code -eq 1 ]; then
                          ((failed_compilations += 1))
                      fi
                      continue  # Skip to the next file on compilation error
                  fi

                  gtimeout $TIMEOUT_DURATION ./compiled.out
                  exit_status=$?

                  if [ $exit_status -eq 1 ]; then
                      ((successful_compilations += 1))
                      echo -e "\a"
                  else
                      ((failed_compilations += 1))
                  fi

                  rm -f ./compiled.out
              fi
          done
          echo -e "\a"

          echo "Memory Sanitizer Failures: $failed_compilations"
          echo "Memory Sanitizer Successes: $successful_compilations"
